name: build-packages
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches: [ $default-branch ]
  workflow_dispatch:
  pull_request:

jobs:
  build-variant:
    runs-on: ${{ matrix.build_os }}
    strategy:
      matrix:
        build_os:
          - ubuntu-latest
          - macos-latest
        vmac_type:
          - II
          #- Plus
          #- SE
        host_platform:
          - lx64
          - wx64
          - mc64
          - mcar
        exclude:
          - build_os: ubuntu-latest
            host_platform: mc64
          - build_os: ubuntu-latest
            host_platform: mcar
          - build_os: macos-latest
            host_platform: lx64
          - build_os: macos-latest
            host_platform: wx64
    env:
      COMMON_FLAGS: "-n minivmac-37-bluescsi -bg 1"
    steps:
      - uses: actions/checkout@v4
      - name: Compile setup tool
        run: gcc -o setup_t setup/tool.c
      - name: Extra arguemnts (Windows)
        if: ${{ matrix.host_platform=='wx64' }}
        run: echo EXTRA_ARGS="-e mgw" >> $GITHUB_ENV
      - name: Extra arguemnts (macOS)
        if: ${{ startsWith(matrix.host_platform, 'mc') }}
        run: echo EXTRA_ARGS="-ev 13000" >> $GITHUB_ENV
      - name: Build dependancies (Windows)
        if: ${{ matrix.host_platform=='wx64' }}
        run: |
          sudo apt install -y mingw-w64
          ln -s /usr/bin/x86_64-w64-mingw32-gcc gcc.exe
          ln -s /usr/bin/x86_64-w64-mingw32-windres windres.exe
          ln -s /usr/bin/x86_64-w64-mingw32-strip strip.exe
          ln -s src SRC
      - name: Generate configuration script
        run: >
          ./setup_t -maintainer "${{ github.actor }}"
          -homepage ${{ github.repositoryUrl }}
          -t ${{ matrix.host_platform }}
          -m ${{ matrix.vmac_type }}
          $EXTRA_ARGS
          $COMMON_FLAGS
          > setup.sh
      - name: SDL workaround
        run: "sed -i '/.*SDL\\.h/i printf \"%s\\n\" \"#define SDL_MAIN_HANDLED\" \\>\\> \"\\$\\{DestFile\\}\"' setup.sh"
      - name: Generate Makefile
        run: "bash ./setup.sh"
      - name: Add . to PATH
        run: echo . >> $GITHUB_PATH
      - name: Compile
        run: make
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: minivmac-${{ matrix.host_platform }}-${{ matrix.vmac_type }}
          # A file, directory or wildcard pattern that describes what to upload
          path: minivmac
