name: build-packages
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches: [ $default-branch ]
  workflow_dispatch:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vmac_type:
          - II
          #- Plus
          #- SE
        host_platform:
          - lx64
    env:
      COMMON_FLAGS: "-n minivmac-37-bluescsi -bg 1"
    steps:
      - uses: actions/checkout@v4
      - name: Compile setup tool
        run: gcc -o setup_t setup/tool.c
      - name: Generate configuration script
        run: >
          ./setup_t -maintainer "${{ github.actor }}"
          -homepage ${{ github.repositoryUrl }}
          -t ${{ matrix.host_platform }}
          -m ${{ matrix.vmac_type }}
          $COMMON_FLAGS
          > setup.sh
      - name: SDL workaround
        run: "sed -i '/.*SDL\\.h/i printf \"%s\\n\" \"#define SDL_MAIN_HANDLED\" \\>\\> \"\\$\\{DestFile\\}\"' setup.sh"
      - name: Generate Makefile
        run: "./setup.sh"
      - name: Compile
        run: make
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: minivmac-${{ matrix.host_platform }}-${{ matrix.vmac_type }}
          # A file, directory or wildcard pattern that describes what to upload
          path: minivmac
