name: make-release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    branches: [ $default-branch ]

permissions:
  contents: write
  
jobs:
  make-release-executables:
    uses: ./.github/workflows/buildpackages.yml
  make-release-packages:
    needs: make-release-executables
    runs-on: ubuntu-latest
    steps:
      - name: 'Grab executables'
        uses: actions/download-artifact@v3
      - run: ls -R
      - name: 'Make ZIPs'
        shell: bash
        run: |
          hosts="lx64 wx64 mc64 mcar"
          for host in $hosts; do
            echo "Creating $host.zip"
            mkdir $host
            mv $host-*/* $host/
            pushd $host
            zip -rv ../$host.zip .
            popd
          done
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ github.event.head_commit.message }}
          draft: true
          prerelease: false
          files: '*.zip'
